# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXDropMenuView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZXDropMenuView

  target 'ZXDropMenuViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZXDropMenuViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'Masonry'
    pod 'ReactiveObjC'
    pod 'JSONModel'
    pod 'SDWebImage'
    pod 'JPFPSStatus'
    pod 'ZXScrollNavigationBar'

end
